#!/bin/sh

dirNames=(Metrics_Aggregations Bucket_Aggregations Pipeline_Aggregations Matrix_Aggregations )
files=(Metrics_Aggregations/Avg_Aggregation.md Metrics_Aggregations/Cardinality_Aggregation.md Metrics_Aggregations/Extended_Stats_Aggregation.md Metrics_Aggregations/Geo_Bounds_Aggregation.md Metrics_Aggregations/Geo_Centroid_Aggregation.md Metrics_Aggregations/Max_Aggregation.md Metrics_Aggregations/Min_Aggregation.md Metrics_Aggregations/Percentiles_Aggregation.md Metrics_Aggregations/Percentile_Ranks_Aggregation.md Metrics_Aggregations/Scripted_Metric_Aggregation.md Metrics_Aggregations/Stats_Aggregation.md Metrics_Aggregations/Sum_Aggregation.md Metrics_Aggregations/Top_hits_Aggregation.md Metrics_Aggregations/Value_Count_Aggregation.md Metrics_Aggregations/Metrics_Aggregations.md Bucket_Aggregations/Adjacency_Matrix_Aggregation.md Bucket_Aggregations/Children_Aggregation.md Bucket_Aggregations/Date_Histogram_Aggregation.md Bucket_Aggregations/Date_Range_Aggregation.md Bucket_Aggregations/Diversified_Sampler_Aggregation.md Bucket_Aggregations/Filter_Aggregation.md Bucket_Aggregations/Filters_Aggregation.md Bucket_Aggregations/Geo_Distance_Aggregation.md Bucket_Aggregations/GeoHash_grid_Aggregation.md Bucket_Aggregations/Global_Aggregation.md Bucket_Aggregations/Histogram_Aggregation.md Bucket_Aggregations/IP_Range_Aggregation.md Bucket_Aggregations/Missing_Aggregation.md Bucket_Aggregations/Nested_Aggregation.md Bucket_Aggregations/Range_Aggregation.md Bucket_Aggregations/Reverse_nested_Aggregation.md Bucket_Aggregations/Sampler_Aggregation.md Bucket_Aggregations/Significant_Terms_Aggregation.md Bucket_Aggregations/Terms_Aggregation.md Bucket_Aggregations/Bucket_Aggregations.md Pipeline_Aggregations/Avg_Bucket_Aggregation.md Pipeline_Aggregations/Derivative_Aggregation.md Pipeline_Aggregations/Max_Bucket_Aggregation.md Pipeline_Aggregations/Min_Bucket_Aggregation.md Pipeline_Aggregations/Sum_Bucket_Aggregation.md Pipeline_Aggregations/Stats_Bucket_Aggregation.md Pipeline_Aggregations/Extended_Stats_Bucket_Aggregation.md Pipeline_Aggregations/Percentiles_Bucket_Aggregation.md Pipeline_Aggregations/Moving_Average_Aggregation.md Pipeline_Aggregations/Cumulative_Sum_Aggregation.md Pipeline_Aggregations/Bucket_Script_Aggregation.md Pipeline_Aggregations/Bucket_Selector_Aggregation.md Pipeline_Aggregations/Serial_Differencing_Aggregation.md Pipeline_Aggregations/Pipeline_Aggregations.md Matrix_Aggregations/Matrix_Stats.md Matrix_Aggregations/Matrix_Aggregations.md Caching_heavy_aggregations.md Returning_only_aggregation_results.md Aggregation_Metadata.md Returning_the_type_of_the_aggregation.md )



for dirName in ${dirNames[@]}
do
		mkdir ${dirName}
done

for file in ${files[@]}
do 
		touch ${file}
		echo "To be Continued!">>${file}
done
