#!/bin/sh

dirNames=(Installing_Elasticsearch Bootstrap_Checks Important_System_Configuration Upgrading_Elasticsearch )
files=(Installing_Elasticsearch/Install_Elasticsearch_with_.zip_or_.tar.gz.md Installing_Elasticsearch/Install_Elasticsearch_with_Debian_Package.md Installing_Elasticsearch/Install_Elasticsearch_with_RPM.md Installing_Elasticsearch/Install_Elasticsearch_on_Windows.md Installing_Elasticsearch/Install_Elasticsearch_with_Docker.md Installing_Elasticsearch/Installing_Elasticsearch.md Configuring_Elasticsearch.md Important_Elasticsearch_configuration.md Secure_Settings.md Bootstrap_Checks/Heap_size_check.md Bootstrap_Checks/File_descriptor_check.md Bootstrap_Checks/Memory_lock_check.md Bootstrap_Checks/Maximum_number_of_threads_check.md Bootstrap_Checks/Maximum_size_virtual_memory_check.md Bootstrap_Checks/Maximum_map_count_check.md Bootstrap_Checks/Client_JVM_check.md Bootstrap_Checks/Use_serial_collector_check.md Bootstrap_Checks/System_call_filter_check.md Bootstrap_Checks/OnError_and_OnOutOfMemoryError_checks.md Bootstrap_Checks/Early-access_check.md Bootstrap_Checks/G1GC_check.md Bootstrap_Checks/Bootstrap_Checks.md Important_System_Configuration/Configuring_system_settings.md Important_System_Configuration/Set_JVM_heap_size_via_jvm.options.md Important_System_Configuration/Disable_swapping.md Important_System_Configuration/File_Descriptors.md Important_System_Configuration/Virtual_memory.md Important_System_Configuration/Number_of_threads.md Important_System_Configuration/Important_System_Configuration.md Upgrading_Elasticsearch/Rolling_upgrades.md Upgrading_Elasticsearch/Full_cluster_restart_upgrade.md Upgrading_Elasticsearch/Reindex_to_upgrade.md Upgrading_Elasticsearch/Upgrading_Elasticsearch.md Stopping_Elasticsearch.md )

for dirName in ${dirNames[@]}
do
		mkdir ${dirName}
done

for file in ${files[@]}
do 
		touch ${file}
		echo "To be Continued!">>${file}
done
